
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  # Configure a private network
  config.vm.network "private_network", type: "dhcp"
  
  # Customize the VirtualBox provider settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4024"  # Allocate 4 GB of memory
    vb.cpus = 4         # Allocate 4 CPU cores
  end
end
